elasticjob:
  reg-center:
    serverLists: 127.0.0.1:2181
    namespace: elastic-job-lite
    base-sleep-time-milliseconds: 1000
    max-sleep-time-milliseconds: 3000
    max-retries: 3
  jobs:
    A01_testJobCronTrigger1:
      elasticJobClass: com.example.elasticjobdemo.job.MyElasticJob
      cron: 0/15 * * * * ?
      timeZone: GMT+08:00
      shardingTotalCount: 3
      shardingItemParameters: 0=0,1=1,2=2
    A01_testJobCronTrigger2:
      elasticJobClass: com.example.elasticjobdemo.job.SpringBootDataflowJob
      cron: 0 0/30 * * * ?
      timeZone: GMT+08:00
      shardingTotalCount: 1
      shardingItemParameters: 0=0
